services:
  oracle-db:
    image: container-registry.oracle.com/database/free:latest
    container_name: kawashi-oracle
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PWD=sua_senha_forte
    volumes:
      - ./oracle-data:/opt/oracle/oradata
    restart: always

  auth-service:
    build: .
    container_name: auth-service-java
    ports:
      - "8080:8080"
    depends_on:
      - oracle-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@oracle-db:1521/FREEPDB1?oracle.net.disableOob=true
      - SPRING_DATASOURCE_USERNAME=system
      - SPRING_DATASOURCE_PASSWORD=sua_senha_forte
      - SPRING_JPA_HIBERNATE_DDL_AUTO=validate
      - SPRING_FLYWAY_BASELINE_ON_MIGRATE=true